eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
   instance:
    ip-address: 192.168.8.124
    prefer-ip-address: true
    instance-id: 192.168.8.124:${spring.application.name}:${server.port}
